const { S } = require('./sanc')

console.log(S.type(undefined).name)
console.log(S.type(null).name)
console.log(S.type(true).name)
console.log(S.type(1).name)
console.log(S.type(1.2).name)
console.log(S.type('string').name)
console.log(S.type(Symbol('x')).name)
console.log(S.type(() => {}).name)
console.log(S.type({ foo: 'bar' }).name)
console.log(S.type(S.Just(1)).name)
console.log(S.type([1, 2, 3]).name)
